config/routes.rb
Rails.application.routes.draw do

  root 'my_library#home'

  get 'login/user' => 'sessions#new_user', as: :login_user
  get 'login/admin' => 'sessions#new_admin', as: :login_admin
  post 'login/user' => 'sessions#create_user'
  post 'login/admin' => 'sessions#create_admin'
  delete 'logout/user' => 'sessions#destroy_user', as: :logout_user
  delete 'logout/admin' => 'sessions#destroy_admin', as: :logout_admin
  get 'signup' => 'users#new'

  resources :users
  resources :admins
  resources :books
  resources :recommended_books

  get '/checkout/book/:id' => 'checkout_histories#show_book', as: :checkout_book
  get '/checkout/user/:id' => 'checkout_histories#show_user', as: :checkout_user
  get '/checkout/create/book/:id' =>  'checkout_histories#create', as: :create_checkout
  get '/checkout/update/book/:id' =>  'checkout_histories#update', as: :update_checkout
  post '/checkout/create/book/:id' => 'checkout_histories#create_admin', as: :create_admin_checkout
  get '/rec_book' => 'recommended_books#user_recommendation', as: :rec_book
  get '/email_notification/book/:id' => 'books#get_notification', as: :email_notification

end

app/controllers/my_library_controller.rb
class MyLibraryController < ApplicationController
  def home
  end
end

app/helpers/my_library_helper.rb
module MyLibraryHelper
end

app/views/my_library/home.html.erb
<%= form_tag(books_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search,params[:search], placeholder: "Search Books", :size => "30" %>
    <%= submit_tag "Search", name: nil  %>
<% end %>

<br/>
<p><%= link_to "View all books", :books %></p>
<%if admin_logged_in? %>
    <p><%= link_to "View all users", :users %></p>
    <p><%= link_to "Add book", new_book_path %></p>
    <p><%= link_to "Add another admin", new_admin_path %></p>
    <p><%= link_to "View all admins", :admins %></p>
    <p><%= link_to "View all book recommendations", recommended_books_path %></p>
<%end%>