config/routes.rb
Rails.application.routes.draw do

  root 'my_library#home'

  get 'login/user' => 'sessions#new_user', as: :login_user
  get 'login/admin' => 'sessions#new_admin', as: :login_admin
  post 'login/user' => 'sessions#create_user'
  post 'login/admin' => 'sessions#create_admin'
  delete 'logout/user' => 'sessions#destroy_user', as: :logout_user
  delete 'logout/admin' => 'sessions#destroy_admin', as: :logout_admin
  get 'signup' => 'users#new'

  resources :users
  resources :admins
  resources :books
  resources :recommended_books

  get '/checkout/book/:id' => 'checkout_histories#show_book', as: :checkout_book
  get '/checkout/user/:id' => 'checkout_histories#show_user', as: :checkout_user
  get '/checkout/create/book/:id' =>  'checkout_histories#create', as: :create_checkout
  get '/checkout/update/book/:id' =>  'checkout_histories#update', as: :update_checkout
  post '/checkout/create/book/:id' => 'checkout_histories#create_admin', as: :create_admin_checkout
  get '/rec_book' => 'recommended_books#user_recommendation', as: :rec_book
  get '/email_notification/book/:id' => 'books#get_notification', as: :email_notification

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 200 },
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6, maximum: 25 }, allow_nil: true

	has_many :checkout_histories, dependent: :destroy
	has_many :books, through: :checkout_histories, dependent: :destroy
	has_many :recommended_books, dependent: :destroy
	has_many :email_notifications, dependent: :destroy
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    before_action :logged_in_user, only: [:edit, :update, :show]
    before_action :right_user,   only: [:edit, :update, :show]
    before_action :logged_in_admin, only: [:index, :destroy]

    def new
      @user = User.new
    end

    def create
     @user = User.new(user_params)
     if User.find_by(email: params[:user][:email])
       flash.now[:error] = "User already exists."
       render 'new'
     else
       if @user.save
         log_in_user @user
         flash[:success] = "Account created successfully."
         redirect_to @user
       else
         flash.now[:error] = @user.errors.full_messages.to_sentence
         render 'new'
       end
     end
   end

   def show
     @user = User.find(params[:id])
   end

   def edit
    @user = User.find(params[:id])
   end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated successfully."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.page(params[:page]).per(20)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.checkout_histories.any? {|val| val.book.status == "Checked out" }
      flash[:error] = "User has checked out books. Cannot be deleted."
      redirect_to users_path
    else
      flash[:success] = "User deleted successfully."
      @user.destroy
      redirect_to users_url
    end
  end

  private
  def user_params
   params.require(:user).permit(:first_name, :last_name, :email,
    :password, :password_confirmation)
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <%= form_for(@user) do |f| %>


      <p><%= f.label :first_name %>
      <%= f.text_field :first_name %></p>

      <p><%= f.label :last_name %>
      <%= f.text_field :last_name %></p>

      <p><%= f.label :password %>
      <%= f.password_field :password %></p>

      <p><%= f.label :re_enter_password %>
      <%= f.password_field :password_confirmation %></p>

      <p><%= f.submit "Update" %></p>
    <% end %>

app/views/users/index.html.erb
<h2>Library Users</h2>
<% if @users.present? %>
    <table border="4" >
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>User Checkout History</th>
        <th>Delete</th>
      </tr>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= link_to "View Checkout history",checkout_user_path(user) %></td>
            <td><%= link_to 'Delete User', user, method: :delete, data: { confirm: "Are you sure you want to delete the user?" } %></td>
            <br/>
          </tr>
      <% end %>
    </table>
    <br/>
    <%= paginate @users %>
    <%= page_entries_info @users %>
    <br/><br/>
<% else %>
    <p>There are currently no users in the library %></p>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>


    <%= form_for(@user) do |f| %>

      <p><%= f.label :first_name %>
      <%= f.text_field :first_name %></p>

      <p><%= f.label :last_name %>
      <%= f.text_field :last_name %></p>

      <p><%= f.label :email %>
      <%= f.email_field :email %></p>

      <p><%= f.label :password %>
      <%= f.password_field :password %></p>

      <p><%= f.label :Re_enter_password %>
      <%= f.password_field :password_confirmation %></p>

      <p><%= f.submit "Register" %></p>
    <% end %>

app/views/users/show.html.erb
<h3>My Account</h3>
<p><%= "First Name : " + @user.first_name %></p>
<p><%= "Last Name :  " + @user.last_name %></p>
<p><%= "Email :      " + @user.email %></p>

<p><%= link_to "See Checkout history", checkout_user_path(@user) %><p/>

<p><%= link_to "See My recommendations", rec_book_path %><p/>

<p><%= link_to "Recommend a Book", new_recommended_book_path %><p/>

<p><%= link_to "Edit Profile", edit_user_path(@user) %></p>