config/routes.rb
Rails.application.routes.draw do

  root 'my_library#home'

  get 'login/user' => 'sessions#new_user', as: :login_user
  get 'login/admin' => 'sessions#new_admin', as: :login_admin
  post 'login/user' => 'sessions#create_user'
  post 'login/admin' => 'sessions#create_admin'
  delete 'logout/user' => 'sessions#destroy_user', as: :logout_user
  delete 'logout/admin' => 'sessions#destroy_admin', as: :logout_admin
  get 'signup' => 'users#new'

  resources :users
  resources :admins
  resources :books
  resources :recommended_books

  get '/checkout/book/:id' => 'checkout_histories#show_book', as: :checkout_book
  get '/checkout/user/:id' => 'checkout_histories#show_user', as: :checkout_user
  get '/checkout/create/book/:id' =>  'checkout_histories#create', as: :create_checkout
  get '/checkout/update/book/:id' =>  'checkout_histories#update', as: :update_checkout
  post '/checkout/create/book/:id' => 'checkout_histories#create_admin', as: :create_admin_checkout
  get '/rec_book' => 'recommended_books#user_recommendation', as: :rec_book
  get '/email_notification/book/:id' => 'books#get_notification', as: :email_notification

end

app/models/book.rb
class Book < ActiveRecord::Base
	#before_save {self.title = title.capitalize, self.author = author.capitalize}
	validates :isbn, presence: true, uniqueness: true
	validates :title, presence: true
	validates :author, presence: true
  has_many :checkout_histories, dependent: :destroy
  has_many :users, through: :checkout_histories, dependent: :destroy
  has_many :email_notifications, dependent: :destroy

  def self.search(search)
     search = search.downcase
     where("lower(title) like :search OR isbn = :search2 OR lower(author) like :search OR lower(description) like :search OR lower(status) = :search2",search2: "#{search}",search: "%#{search}%")
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :logged_in_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC").page(params[:page]).per(20)
    else
      @books = Book.page(params[:page]).per(20)
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book added successfully!"
      redirect_to @book
    else
      flash.now[:error] = @book.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
    @users = @book.users
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:success] = "Book updated successfully!"
      redirect_to @book
    else
      flash.now[:error] = @book.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.status == "Checked out"
      flash[:error] = "Book is checked out. Cannot be deleted!"
      redirect_to books_path
    else
      @book.destroy
      flash[:success] = "Book deleted successfully!"
      redirect_to books_path
    end
  end

  def get_notification
    @book = Book.find(params[:id])
    email_notification = current_user.email_notifications.new(book: @book)
    if email_notification.save
      flash[:success] = "Successfully subscribed to notification."
      redirect_to books_path
    else
      flash[:error] = email_notification.errors.full_messages.to_sentence
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:isbn, :title, :description, :author, :status)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Edit book details</h1>

<%= form_for @book, url: book_path(@book), method: :patch do |f|%>
    <%= f.text_field :isbn, :placeholder => 'ISBN' %>
    <%= f.text_field :title, :placeholder => 'Title' %>
    <%= f.text_field :author, :placeholder => 'Authors' %>
    <%= f.text_field :description, :placeholder => 'Description' %>
    <%= f.submit 'Update Book' %>
<%end%>

app/views/books/index.html.erb
<%= form_tag(books_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Books", :size => "30" %>
    <%= submit_tag "Search", name: nil  %>
<% end %>
<br/>
<p><%= link_to "Back", root_path %></p>

<h2>Books</h2>

<% if @books.present? %>
    <table border="4" >
      <col width="40">
      <col width="100">
      <col width="100">
      <col width="120">
      <col width="100">
      <col width="100">
      <col width="100">
      <tr>
        <th>ISBN</th>
        <th>Title</th>
        <th>Authors</th>
        <th>Description</th>
        <th>Status</th>
        <% if user_logged_in? %>
          <th></th>
        <% end %>
        <% if admin_logged_in? %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
      <% @books.order("created_at DESC").each do |book| %>
          <tr>
            <td><%= link_to book.isbn, book_path(book) %></td>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.description %></td>
            <td><%= book.status %></td>
            <% if user_logged_in? %>
               <% if book.status == "Available" %>
                   <td><%= link_to 'Checkout', create_checkout_path(book) %></td>
               <%end%>
               <% if (book.status == "Checked out") %>
                    <% if current_user == book.checkout_histories.last.user %>
                       <td><%= link_to 'Return Book', update_checkout_path(book), data: { confirm: 'Are you sure you want to return the book?'} %></td>
                   <%else%>
                        <% if book.email_notifications.any? {|ent| (ent.sent == false) && (ent.user_id == current_user.id) } %>
                            <td>Already subscribed to email!</td>
                        <% else %>
                            <td><%= link_to 'Get Email Notification', email_notification_path(book) %></td>
                        <% end %>
                   <%end%>
               <%end%>
            <%end%>
            <% if admin_logged_in? %>
              <td><%= link_to 'Edit', edit_book_path(book) %></td>
              <td><%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure you want to delete the book?'} %></td>
            <%end%>
          </tr>
      <%end%>
    </table>

    <%= paginate @books %>
    <%= page_entries_info @books %>
<% else %>
    <p>There are no books containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/books/new.html.erb
<h1>Add new book</h1>

<%= form_for @book, url: books_path do |f|%>
    <%= f.text_field :isbn, :placeholder => 'ISBN' %>
    <%= f.text_field :title, :placeholder => 'Title' %>
    <%= f.text_field :author, :placeholder => 'Authors' %>
    <%= f.text_field :description, :placeholder => 'Description' %>

    <%= f.submit 'Add Book' %>
<%end%>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><%= "ISBN : " + @book.isbn %></p>
<p><%= "Authors : " + @book.author %></p>
<p><%= "Description : " + @book.description %></p>
<p><%= "Status : " + @book.status %>
  <% if (@book.status == "Checked out") && (admin_logged_in?) %>
      <%if admin_logged_in? %>
          by <%= @book.checkout_histories.order("issued_at DESC").first.user.email unless @book.checkout_histories.order("issued_at DESC").first.nil? %></p>
      <%end%>
  <%end%>
  <% if admin_logged_in? %>
      <p><%= link_to "See Checkout history", checkout_book_path(@book) %><p/>
  <%end%>
  <br/>


  <%if user_logged_in? %>
      <% if @book.status == "Available" %>
          <br/>
          <%= link_to "Checkout", create_checkout_path(@book)%>
      <% else !(@book.checkout_histories == nil) %>
          <% if @book.checkout_histories.order("issued_at DESC").first.user == current_user %>
              <br/>
              <%= link_to "Return Book", update_checkout_path(@book), data: { confirm: 'Are you sure you want to return the book?'} %>
          <%else%>
              <% if @book.email_notifications.any? {|ent| (ent.sent == false) && (ent.user_id == current_user.id) } %>
                  <br/><td>Already subscribed to email!</td>
              <% else %>
                  <br/><td><%= link_to 'Get Email Notification', email_notification_path(@book) %></td>
              <% end %>
          <%end%>
      <% end %>
  <% elsif admin_logged_in? %>
      <% if @book.status == "Available" %>
          <%= form_for :user, url:  create_admin_checkout_path(@book)  do |f|%>
              <%= f.label "Enter library member EmailID: " %>
              <%= f.text_field :email%><br/>
              <%= f.submit "Checkout Book" %>
          <% end %>
      <% else !(@book.checkout_histories == nil)%>
          <%= link_to "Return Book", update_checkout_path(@book) %><br/>
      <%end%>
      <br/>
      <%= link_to 'Edit', edit_book_path(@book) %>&nbsp;&nbsp
      <%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: 'Are you sure you want to delete the book?'} %>
  <%end%>

<br/><br/>
<%= link_to "View all books", books_path %>