config/routes.rb
Rails.application.routes.draw do

  root 'my_library#home'

  get 'login/user' => 'sessions#new_user', as: :login_user
  get 'login/admin' => 'sessions#new_admin', as: :login_admin
  post 'login/user' => 'sessions#create_user'
  post 'login/admin' => 'sessions#create_admin'
  delete 'logout/user' => 'sessions#destroy_user', as: :logout_user
  delete 'logout/admin' => 'sessions#destroy_admin', as: :logout_admin
  get 'signup' => 'users#new'

  resources :users
  resources :admins
  resources :books
  resources :recommended_books

  get '/checkout/book/:id' => 'checkout_histories#show_book', as: :checkout_book
  get '/checkout/user/:id' => 'checkout_histories#show_user', as: :checkout_user
  get '/checkout/create/book/:id' =>  'checkout_histories#create', as: :create_checkout
  get '/checkout/update/book/:id' =>  'checkout_histories#update', as: :update_checkout
  post '/checkout/create/book/:id' => 'checkout_histories#create_admin', as: :create_admin_checkout
  get '/rec_book' => 'recommended_books#user_recommendation', as: :rec_book
  get '/email_notification/book/:id' => 'books#get_notification', as: :email_notification

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   <h1 align="center" > <%= link_to "Library System", '#', id: "logo" %></h1>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_url %></li>
        <% if !(user_logged_in? || admin_logged_in?) %>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in as Admin", login_admin_path %></li>
          <li><%= link_to "Log in as Member", login_user_path %></li>
        <% else %>
            <li><%= link_to "My Account", user_logged_in? ? current_user : current_admin %></li>
            <li><%= link_to "Log Out", user_logged_in? ? logout_user_path : logout_admin_path , method: :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <% if message_type == "success" %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% else %>
            <div class="alert alert-info"><%= message %></div>
        <% end %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>